site_name: "Cognitive Cloud Open Development Documentation"
nav:
  - "Overview": "index3.md"
  - "Personas":
    - "Admin": "personas/admin.md"
    - "Mentor": "personas/mentor.md"
    - "Partner": "personas/partner.md"
    - "Faculty": "personas/faculty.md"
    - "Developer": "personas/developer.md"
    
  - "CCode-Open-Hub Profiles":
    - "Assets": 
      - "Cloud Education": 
        - "Blockchain": "components/assets/cloudedu/blockchain.md"
        - "IBM Skill Academy": "components/assets/cloudedu/skillacademy.md"
        - "Watson and Cloud": "components/assets/cloudedu/watsoncloud.md"  
      - "Cloud Research": 
        - "Cloud Telescope Network": "components/assets/cloudresearch/ctn.md" 
        - "Cognitive Prosthetic Innovations": "components/assets/cloudresearch/cogprosinnov.md"
        - "Neuro-Electro-Chemical Transmitter Analytics Research": "components/assets/cloudresearch/necanalytics.md"
      - "Cloud Technology/Services": 
        - "Enterprise Exception Handler": "components/assets/cloudtechno/eeh.md"
        - "Enterprise Test Robot": "components/assets/cloudtechno/etr.md"
        - "SQL Catalog": "components/assets/cloudtechno/sqlcatalog.md"
        - "Vortex Pattern": "components/assets/cloudtechno/vortex.md"
        - "Universal Topology": "components/assets/cloudtechno/univtopology.md"
      
    - "Framework":
      - "Dashboard": "components/frameworks/dashboard/dashboard.md"
      - "Event": "components/frameworks/event/event.md"
      - "Framework": "components/frameworks/framework.md"
    
  - "Technology":
    - "IBM":
      - "Cloud": "technology/ibm/cloud.md"
      - "OpenShift": "technology/ibm/openshift.md"
      - "IBM": "technology/ibm/ibm.md"
    - "Open Source":
      - "Docker": "technology/open-source/docker.md"
  
  - "Components": "index.md"    
  
  - "Projects":
    - "[[%Year%]]":
      - "[[%Project@id%]]": "projects/2021/ccode-2021-aot.md"

  - "Release":
    - "1.0.0": "release/notes-1.0.0.md"

  - "Community":
    - "[[%Community@name%]]": "community/IBM Developer.md"

  - "Collaborators": "collaborators.md"

# Project Information
site_url: "https://github.com/ibm-asset/ccode"
site_description: Cognitive Cloud Open Development
site_author: IBM Services Asset

# Repository Information
repo_name: 'ibm-asset/ccode-docs'
repo_url: 'https://github.com/ibm-asset/ccode-docs'
docs_dir: 'docs'
site_dir: 'site'
remote_branch: 'gh-pages'
remote_name: 'origin'
    

theme:
  name: material
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
    size: 10px
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
extra_css: [stylesheets/extra_css.css]
extra_javascript:
  - javascripts/paging.js
  - javascripts/extra.js

plugins:
    - search
    - markdownextradata: {}

extra:
  cognitive_cloud:
    asset_name: Open Development Hub
